### ISSUE TITLE
Consider Zenodo

### ISSUE THREAD

**Issue by gncs** [dockstring/dockstring#133]
This project https://www.atom3d.ai/ is using Zenodo https://zenodo.org/. I signed up with my GitHub account and it looks pretty good. @mgarort, could you try uploading stuff there and share the link with us? I am no longer a big fan of figshare and if we can find a good alternative I would be happy. @AustinT, what are your thoughts?

**Comment by AustinT** [comment]
We put everything on figshare already [here](https://figshare.com/articles/dataset/dockstring_dataset/16511577), so I'm closing this issue.
