### ISSUE TITLE
Make dockstring available on `conda-forge`

### ISSUE THREAD

**Issue by AustinT** [dockstring/dockstring#137]
This helps conda users install it more easily.

**Comment by gncs** [comment]
I would say that PyPI would work, too. Here, from the Teams chat.

I did some research on how to publish dockstring on PyPI (for simple installation through pip). Miguel Garcia Ortegon:

- Read this: https://realpython.com/pypi-publish-python-package
- Create an account on the PyPI test platform: https://test.pypi.org/
- Create an account on the real PyPI: https://pypi.org/

**Comment by AustinT** [comment]
Update on this: I looked into this and a big issue is dependencies. If I add our pinned rdkit version and pinned openbabel version as dependencies (`install_requires=[...]`), then pip installation fails since apparently our specific versions of these packages are not available on pypi. It looks like one would need to manually install the dependencies first (e.g. using conda), then install dockstring. If this is the case I don't really see the point of putting it on pypi; they might as well just install it from github.

We could still put it on conda-forge, but we would need to decide how strict we want to make the python version dependency. Should we force people to exactly use 3.7.10? This would minimize chances of library behaviour changes, but will not be sustainable over time (e.g. python 3.7 will reach end of life next year).

Overall, what are your thoughts on hosting dockstring and pinning it to dependencies @gncs @mgarort ?

**Comment by AustinT** [comment]
Done now. See: https://anaconda.org/conda-forge/dockstring
