### ISSUE TITLE
Scores don't match

### ISSUE THREAD

**Issue by zhengxu001** [dockstring/dockstring#144]
I've come across some scores in the provided [dataset](https://figshare.com/articles/dataset/dockstring_dataset/16511577) that don't match the scores computed via the Dockstring python library. For example:

```python
from dockstring import load_target
import pandas as pd

original_df = pd.read_csv(
        '/data2/xu-training-data/char-rnn/data/dockstring/dockstring-dataset.tsv',
        sep="\t",
        usecols=['smiles', 'F2']
    ).dropna().reset_index(drop=True)

selected_item = original_df[original_df['smiles'] == 'O=C(NCCCOC)C(C1=NC=2C(N=C1N3CCCC3)=CC=CC2)C#N']
print(selected_item['F2'].values)


target = load_target("F2")
score, _ = target.dock("O=C(NCCCOC)C(C1=NC=2C(N=C1N3CCCC3)=CC=CC2)C#N")
print(f"score={score:.3g}. END OF SCRIPT.")
```
The output is:
```
[-7.8]
score=-7.2. END OF SCRIPT.
```

The packages that could be relevant to this problem can be found:
```
# Name                    Version                   Build  Channel
dockstring                0.2.0                    pypi_0    pypi
numpy                     1.21.5           py37he7a7128_2
pandas                    1.3.5            py37h8c16a72_0
python                    3.7.13               h12debd9_0
pytorch                   1.11.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
rdkit                     2020.09.1.0      py37hd50e099_1    rdkit
```

What could be the problem with the unmatched scores? Do we need any pre-processing steps on the ligands? Thanks!

**Comment by mgarort** [comment]
Hi @zhengxu001 ,

Thanks for your message. I have run your script on a fresh DOCKSTRING installation and I get the desired `-7.8` value. In my opinion, the main suspect among the packages you show is RDKit. You are using version `2020.09.1.0` but the version required by DOCKSTRING is `2021.03.3` (see the file [environment.yml](https://github.com/dockstring/dockstring/blob/main/environment.yml)). Therefore, it is very possible that molecules are embedded into 3D coordinates slightly differently, which would naturally result in slightly different docking scores.

Could you please try running your script on a fresh DOCKSTRING installation with the required dependencies (i.e. do `conda env create -f environment.yml` in step 2 of the [installation instructions](https://github.com/dockstring/dockstring#installation)) and check whether you get the same score as in the dataset?

**Comment by zhengxu001** [comment]
Thank you @mgarort. 

I changed the Rdkit to `2021.03.3`, and the predicted scores from this lib are the same as the scores in the given dataset!

**Comment by AustinT** [comment]
@mgarort do you think we should add a PR which outputs a warning if the dependencies don't match? That might mitigate issues like this in the future.
