### ISSUE TITLE
boost::thread_resource_error

### ISSUE THREAD

**Issue by wdorji** [dockstring/dockstring#149]
Hello, I am using a remote linux desktop and I followed the steps outlined in the installation to clone the repo, create a new environment and then pip install dockstring which all ran successfully. However when I try to run the simple_example.py in the tutorials folder, I get the following error:

Traceback (most recent call last):
  File "tutorials/simple_example.py", line 7, in <module>
    score, _ = target.dock("CC1=C(C(=O)N2CCCCC2=N1)CCN3CCC(CC3)C4=NOC5=C4C=CC(=C5)F")
  File "/users/wdorji/.conda/envs/dockstring/lib/python3.7/site-packages/dockstring/target.py", line 192, in dock
    self._dock_pdbqt(ligand_pdbqt, vina_logfile, vina_outfile, seed=seed, num_cpus=num_cpus)
  File "/users/wdorji/.conda/envs/dockstring/lib/python3.7/site-packages/dockstring/target.py", line 138, in _dock_pdbqt
    raise VinaError(f'Docking with Vina failed: {output}')
dockstring.errors.VinaError: Docking with Vina failed: #################################################################
# If you used AutoDock Vina in your work, please cite:          #
#                                                               #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, Journal of Computational Chemistry 31 (2010)  #
# 455-461                                                       #
#                                                               #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
# Please see http://vina.scripps.edu for more information.      #
#################################################################

WARNING: The search space volume > 27000 Angstrom^3 (See FAQ)
Detected 24 CPUs
WARNING: at low exhaustiveness, it may be impossible to utilize all CPUs
Reading input ... done.
Setting up the scoring function ... done.
Analyzing the binding site ... done.
Using random seed: 974528263
Performing search ... 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

An error occurred: boost::thread_resource_error. 

Is there any way to solve this issue? Thanks

**Comment by AustinT** [comment]
Hello @wdorji , thanks for trying to use dockstring! This is a strange error which we've never seen before. Do you by any chance have a second installation of autodock vina on your remote desktop? If so, my guess is that this is the source of the problem.

Otherwise, could you give us some information about your system? For example, the exact operating system and the output of `uname -a`?

@mgarort maybe you can give a command which @wdorji  could run on the remote machine which would test the vina installation specifically?

**Comment by AustinT** [comment]
Closing due to lack of response. Re-open if necessary.
