### ISSUE TITLE
How to get protein sequences correspoding to various (58) targets from your paper?

### ISSUE THREAD

**Issue by RajGhugare19** [dockstring/dockstring#150]
I would like to obtain the 2d protein representation for the 58 targets from your paper. Could you help me on how to do this?

**Comment by AustinT** [comment]
Hi Raj, thanks for your interest in dockstring. I'm not sure what kind of 2D representation you have in mind: you can use pymol to visualize the proteins in 3D, and you could get other information from [pdb](https://www.rcsb.org/). @mgarort do you have any more suggestions?

I will close this issue for now because it is not really an issue with dockstring, but feel free to comment again if you have extra suggestions!

**Comment by RajGhugare19** [comment]
You are right, it is not an issue with dockstring. Sorry for not being clearer before.

I would like the string representation of the protein targets. This representation of proteins has been used by previous paper to predict the ligand-target affinity. For example this paper - DeepDTA: deep drug–target binding affinity prediction.

For example for target DRD1, this page(https://www.uniprot.org/uniprotkb/P21728/entry#sequences) has given the corresponding target sequence of length 446.

**Comment by AustinT** [comment]
This is where we got our proteins from. https://dude.docking.org/targets

I think you would need to find the sequences manually.

For the particular target you mentioned (CYP2C9), I think it might actually be a typo of [CP2C9](https://dude.docking.org/targets/cp2c9). @mgarort  can you comment?

**Comment by RajGhugare19** [comment]
> I think you would need to find the sequences manually.
Looks like it. 

CYP2C9 -- I obtained this name from both your (1) arxiv paper and after using the (2) function dockstring.list_all_target_names()

(1) Table 2 page 17 of - https://arxiv.org/pdf/2110.15486.pdf
(2) The name in github repo  - https://github.com/dockstring/dockstring/blob/5d1cda7f8fb205a15fe962ec4fda251df54794fa/dockstring/resources/targets/CYP2C9_target.pdbqt

Thank you for all your answers!

**Comment by AustinT** [comment]
@RajGhugare19 I meant it might be *our* typo, not your typo. I am asking my collaborator who compiled the dataset to comment.

**Comment by RajGhugare19** [comment]
Got it! If you are sure that this is a typo, please let me know about what the original names should be. I am kind of a newbie in chemistry.

Thanks a lot!

**Comment by mgarort** [comment]
Hi @RajGhugare19 

I don't think it is a typo. We are using the names of the genes of the proteins according to their HUGO nomenclature. You can search for each gene (and the corresponding protein) here  https://www.genenames.org/ From that information it should be easy to get the protein sequence. For example, you can go to [the HUGO page for CYP2C9](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:2623) and go to "Protein resources" to find the link to Uniprot.

DUD-E names are occasionally different from the HUGO name. We chose HUGO for all proteins for consistency. Hopes this makes sense.

**Comment by RajGhugare19** [comment]
Hello @mgarort :)

Ahh, now I understand. Thanks a lot for your help.
