### ISSUE TITLE
Augmented dataset for more proteins available?

### ISSUE THREAD

**Issue by ddomingof** [dockstring/dockstring#165]
Hi @mgarort @AustinT,

I am interested in using your dataset (DockString) to train a model and I wanted to know if by chance you have the docking scores of the 250,000 compounds for other proteins than the 58 you present in the paper.

Basically, I would like to augment your dataset to go beyond 1,000 proteins instead of 58.
I guess other people have had this idea before and that's why I ask, in case it's already done and you don't have to run it all by me.

In case something like this doesn't exist, which I'm afraid will be the case, how long would you estimate it would take to run this? I calculated that it will take quite a lot given each docking experiment could take up to 1 min, so I was wondering if when you generated the dataset you parallelized the code or something?

Also, I guess running this script iterating over all the Protein and compound combinations is all that needs to be done https://github.com/dockstring/dockstring/blob/main/tutorials/simple_example.py

Thanks,

Best regards

**Comment by AustinT** [comment]
Hi, I don't think we have any more large-scale data. We informally/sporadically tried a few other proteins but never docked the 250k molecules against anything.

I agree with your estimate of ~1 CPU minute/molecule (although the time is larger for larger molecules). When we computed the dataset we just divided the molecules into small chunks of ~100 molecules and submitted many jobs to Cambridge University's High-Performance computing cluster, so there was no fancy parallelism. The script we used was essentially the "simple example" script you pointed to (although with more logging).

Hope this helps: I will close the issue, but feel free to post or email us if you want more details.
