### ISSUE TITLE
API of bechmark tasks

### ISSUE THREAD

**Issue by mgarort** [dockstring/dockstring#58]
Similarly to how targets are loaded

```
from dockgym import load_target

target = load_target(name)
score = target.dock(smiles)
```

we can have an analogous syntax for loading benchmark tasks

```
from dockgym import load_benchmark

benchmark = load_benchmark(name)
score = benchmark.eval(smiles)
```

I am not sure about:
- `benchmark`: it could be "test", for example. Although "benchmark" is catchier, in my opinion.
- `eval`: it could be "evaluate", "test", "score" (although "score" is too similar to "docking scores", so probably not a good idea), "metric", etc.

What do you think?

**Comment by AustinT** [comment]
> The bundle i.e., repo, should contain the dataset, benchmarks, and wrapper.
> 
> For the benchmarks, we should provide the following:
> 
>     * Regression: nothing to do here
> 
>     * Screening: script or function that takes a list of SMILES and outputs the relevant statistics
> 
>     * Optimization: objective functions

Following up on this:

- regression: nothing to do
- Screening: the statistics list is only related to the benchmark and IMO should not be part of the package itself. I opened [this issue](https://github.com/dockstring/benchmarks/issues/1) in the benchmarks repo instead.
- Optimization: included in #139 

Therefore I think it makes sense to close this issue.
