### ISSUE TITLE
dockstring Dataset

### ISSUE THREAD

**Issue by mgarort** [dockstring/dockstring#94]
Actives for at least one target with `A`.
Not active for any measured target with `NA`. There may be activity against some of the 58 targets, but it didn't show up in those that were measured.

All SMILES in the file should be parsable (only 34 of the selection consisting of all actives plus 150k inactives were not parsable).

https://drive.google.com/file/d/1suQB4KLDEic9sQkJv1SyurIZtrst0Wgt/view?usp=sharing

**Comment by AustinT** [comment]
Done [here](https://github.com/dockstring/dataset).
